=== datenanfragen/data/schema-supervisory-authorities.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Datenanfragen.de supervisory authority database record",
	"description": "A single record of the Datenanfragen.de supervisory authority database. It represents the contact information of an authority specifically for lodging complaints.\nMore information and access to the whole database at: https://github.com/datenanfragen/companies",
	"type": "object",
	"properties": {
		"slug": {
			"type": "string",
			"title": "Slug",
			"pattern": "^[a-z0-9-]+$",
			"description": "A unique identifier for the supervisory authority record. Also defines the filename."
		},
		"relevant-countries": {
			"type": "array",
			"title": "Relevant countries",
			"description": "A list of countries the record is relevant for. The countries can either be an ISO 3166-1 alpha-2 country code or 'all'. If a supervisory authority offers its services in English and isn't explicitly restricted to certain countries, 'all' should be specified.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"pattern": "^([a-z]{2}|all)$"
			}
		},
		"name": {
			"type": "string",
			"description": "The official name of the authority.",
			"title": "Name"
		},
		"address": {
			"type": "string",
			"title": "Address",
			"description": "The address where the authority can be reached to lodge complaints. Has to include the country (either in the country's native language or in English) in the last line and should be formatted according to the standards of the respective country.",
			"format": "text"
		},
		"phone": {
			"type": "string",
			"title": "Phone",
			"description": "A phone number where the authority can be reached for privacy-related inquires and complaints. Has to be in the standard international format and include the country code.",
			"pattern": "^\\+\\d+ \\d+ [\\d ]+$"
		},
		"fax": {
			"type": "string",
			"title": "Fax",
			"description": "A fax number where the authority can be reached for privacy-related inquires and complaints. Has to be in the standard international format and include the country code.",
			"pattern": "^\\+\\d+ \\d+ [\\d ]+$"
		},
		"email": {
			"type": "string",
			"title": "Email",
			"description": "An email address where the authority can be reached to lodge complaints. Preferably a specific complaint@[domain.tld] address if available.",
			"format": "idn-email"
		},
		"pgp-fingerprint": {
			"type": "string",
			"title": "PGP key fingerprint",
			"description": "Fingerprint of the PGP key of the email address used to lodge complaints with the authority. The PGP key should be found by this key on public keyservers. Please check the key thoroughly before entering it.",
			"format": "text"
		},
		"pgp-url": {
			"type": "string",
			"title": "PGP key URL",
			"description": "URL, where the PGP key of the email address used to lodge complaints with the authority can be downloaded. The protocol *must* be https and the domain has to belong to the repective authority. Please check the key thoroughly before entering it.",
			"format": "uri"
		},
		"web": {
			"type": "string",
			"title": "Website",
			"description": "The authority's main website.",
			"format": "uri"
		},
		"sources": {
			"type": "array",
			"title": "Sources",
			"description": "A list of sources for the record. Preferably from the authority's official website.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"format": "uri"
			}
		},
		"complaint-language": {
			"type": "string",
			"title": "Complaint language",
			"description": "The language complaint to the authority should be in. Has to be an ISO 639-1 language code. If not specified, fallback to the interface language.",
			"pattern": "^[a-z]{2}$"
		},
		"suggested-transport-medium": {
			"type": "string",
			"title": "Suggested transport medium",
			"description": "The transport medium a user should use for their privacy-related inquires and requests. If a PGP key is available, 'email' should be specified. The default is a fallback chain as follows: fax -> letter -> email.",
			"enum": [ "fax", "letter", "email" ]
		},
		"comments": {
			"type": "array",
			"title": "Comments",
			"description": "A list of notes relevant to the record.",
			"items": {
				"type": "string",
				"format": "text"
			}
		}
	},
	"additionalProperties": false,
	"required": [ "slug", "relevant-countries", "name", "address", "sources" ]
}

=== datenanfragen/data/companies/unilever.json
{
    "slug": "unilever",
    "relevant-countries": [
        "all"
    ],
    "name": "Unilever N.V.",
    "address": "Weena 455\nPO Box 760\n3000 DK Rotterdam\nNetherlands",
    "email": "unilever.privacy@unilever.com",
    "web": "https://www.unilever.com/",
    "sources": [
        "https://github.com/datenanfragen/data/issues/393",
        "https://www.unilevernotices.com/global/en_gb/privacy-notice/notice.html"
    ],
    "suggested-transport-medium": "email"
}

=== datenanfragen/data/supervisory-authorities/dkdi.json
{
    "slug": "dkdi",
    "relevant-countries": [
        "dk"
    ],
    "name": "Datatilsynet (Data Inspectorate of Denmark)",
    "address": "Carl Jacobsens Vej 35\n2500 Valby\nDenmark",
    "phone": "+45 33 19 32 00",
    "fax": "+45 33 19 32 18",
    "email": "dt@datatilsynet.dk",
    "web": "https://www.datatilsynet.dk/",
    "sources": [
        "https://www.datatilsynet.dk/kontakt/"
    ],
    "complaint-language": "da"
}

=== datenanfragen/data/supervisory-authorities/dekathdsz.json
{
    "slug": "dekathdsz",
    "relevant-countries": [
        "de"
    ],
    "name": "Katholisches Datenschutzzentrum (KdöR)",
    "address": "Brackeler Hellweg 144\n44309 Dortmund\nDeutschland",
    "phone": "+49 231 13 89 85 0",
    "fax": "+49 231 13 89 85 22",
    "email": "info@kdsz.de",
    "web": "https://www.katholisches-datenschutzzentrum.de/",
    "sources": [
        "https://www.katholisches-datenschutzzentrum.de/wir-ueber-uns/team-katholisches-datenschutzzentrum/",
        "https://www.datenschutz-kirche.de/%C3%BCbersicht_aufsichtsbeh%C3%B6rden"
    ],
    "complaint-language": "de",
    "comments": [
        "Zuständig für nordrhein-westfälische Bistümer:\n\nBistum Aachen\nBistum Essen\nErzbistum Köln\nBistum Münster (nordrhein-westfälischer Teil)\nErzbistum Paderborn"
    ]
}

=== datenanfragen/data/companies/evolutionjobs.json
{
    "slug": "evolutionjobs",
    "relevant-countries": [
        "gb"
    ],
    "name": "Evolution Recruitment Solutions Ltd",
    "address": "The Genesis Centre\nBirchwood\nWarrington\nWA3 7BH\nUnited Kingdom",
    "email": "privacy@evolutionjobs.com",
    "web": "https://www.evolutionjobs.com/uk/",
    "sources": [
        "https://www.iubenda.com/privacy-policy/54951181",
        "https://github.com/datenanfragen/data/issues/191"
    ],
    "suggested-transport-medium": "email"
}

=== datenanfragen/data/supervisory-authorities/bayldb.json
{
    "slug": "bayldb",
    "relevant-countries": [
        "de"
    ],
    "name": "Der Bayerische Landesbeauftragte für den Datenschutz",
    "address": "Postfach 22 12 19\n80502 München\nDeutschland",
    "phone": "+49 89 2126 72 0",
    "fax": "+49 89 2126 72 50",
    "email": "poststelle@datenschutz-bayern.de",
    "pgp-fingerprint": "AC2D 2383 4CE5 9AA0 C034 E145 8DC1 1C88 7063 3354",
    "pgp-url": "https://www.datenschutz-bayern.de/download/BayerDatenschutzbeauftragter.asc",
    "web": "https://www.datenschutz-bayern.de/",
    "sources": [
        "https://www.datenschutz-bayern.de/vorstell/impressum.html"
    ],
    "complaint-language": "de",
    "suggested-transport-medium": "email",
    "comments": [
        "Für Beschwerden gegen Unternehmen ist es empfohlen sich an das Bayerische Landesamt für Datenschutzaufsicht zu wenden. Bei Beschwerden oder Anfragen zu öffentlichen Stellen ist jedoch der Landesdatenschutzbeauftragte der korrekte Ansprechpartner."
    ]
}
